version: 2
jobs:
  test:
    working_directory: ~/app
    docker:
      - image: circleci/node:12.16
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-dependencies
          command: "npm install"
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: linting
          command: "npm run lint"
  deploy:
    working_directory: ~/app
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Editor Master to Heroku
          command: git push https://git.heroku.com/$EDITOR_HEROKU.git master
workflows:
  version: 2
  build:
    jobs:
      - test
      - deploy:
          requires:
            - test
